---
title: "Untitled"
author: "Chris Baker"
date: "11/02/2019"
output: html_document
---
# processes GIS files mostly in preparation for making figures of study site
# potentially with results overlaid

# see e.g.https://datacarpentry.org/r-raster-vector-geospatial/06-vector-open-shapefile-in-r/
# and https://www.ecologi.st/post/spatial-data-in-r-2-a-practical-example/

# Note. download DEM data from USGS earth explorer:
# https://earthexplorer.usgs.gov

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(root.dir="/Users/chris/Documents/work/leeches/leeches2018/gis")
```

```{r}
#install.packages("sf")
library("sf")
library("gplots")
library("ggrepel")
library("readxl")
library("viridis")
library("raster")
#library("rgdal")
#install.packages("spData")
library("fasterize")
library("rasterVis")
library("rgl")
library("magick")
library("tidyverse")
library("egg")
```

```{r}
rm(list=ls())
```

```{r get data}
# Ailaoshan polygons
    ailaoshan.polygons <- st_read("ailaoshan_polygons/study_area.shp")

# SRTM data
# this can probably be downloaded directly using some R package but we have it locally here
    ailaoshan.srtm <- list()
    ailaoshan.srtm[[1]] <- raster("srtm_data/n23_e100_1arc_v3.tif")
    ailaoshan.srtm[[2]] <- raster("srtm_data/n23_e101_1arc_v3.tif")
    ailaoshan.srtm[[3]] <- raster("srtm_data/n24_e100_1arc_v3.tif")
    ailaoshan.srtm[[4]] <- raster("srtm_data/n24_e101_1arc_v3.tif")
    ailaoshan.srtm[[5]] <- raster("srtm_data/n25_e100_1arc_v3.tif")
    ailaoshan.srtm[[6]] <- raster("srtm_data/n25_e101_1arc_v3.tif")
```

```{r add Polygon_ID to ailaoshan.polygons}
# OBJECTID in ailaoshan.polygons is incremented by 1 compared to Polygon_ID but the datasets otherwise appear to be the same:
    # load(file="../Ailaoshan_environmental.Rdata")
    # env.data$Polygon_ID == as.numeric(ailaoshan.polygons$OBJECTID) - 1
    # round(env.data$shape_perimeter,2) == round(as.numeric(ailaoshan.polygons$Shape_Leng),2)
    # round(env.data$shape_area_ha,2) == round(as.numeric(ailaoshan.polygons$Shape_Area),2)
    # etc

ailaoshan.polygons <- data.frame(ailaoshan.polygons, Polygon_ID = as.numeric(ailaoshan.polygons$OBJECTID) - 1) %>%
    select(OBJECTID, Polygon_ID, everything()) %>% st_sf()
```

```{r examine Ailaoshan polygons, eval=FALSE}
st_geometry_type(ailaoshan.polygons)
st_crs(ailaoshan.polygons)
extent(ailaoshan.polygons)

ailaoshan.polygons %>%
    ggplot() + geom_sf(size = 0.1, color = "black", fill = "burlywood2") + ggtitle("Ailaoshan") + coord_sf()
```

```{r process SRTM data}
# merge srtm tiles into one big raster
    ailaoshan.srtm <- do.call(merge, ailaoshan.srtm)

# crop to a little outside Ailaoshan nature reserve
    ailaoshan.srtm.crop <- crop(ailaoshan.srtm, extent(100.6, 101.6, 23.9, 25.1))

# reproject and crop SRTM data}
# R typically uses the PROJ.4 conventions for cartographic projections (or coordinate reference systems - CRS).
# Check out http://proj4js.org or http://spatialreference.org/ or google for the “proj4string” for various coordinate reference systems.

# note projection does not match that for Ailaoshan polygons:

    st_crs(ailaoshan.polygons)
    proj4string(ailaoshan.srtm.crop)

    extent(ailaoshan.polygons)
    extent(ailaoshan.srtm.crop)

# so reproject data

    ailaoshan.polygons.crs <- st_crs(ailaoshan.polygons)$proj4string
    ailaoshan.srtm.reproj <- projectRaster(ailaoshan.srtm.crop, crs = CRS(ailaoshan.polygons.crs))

# now projection should match Ailaoshan polygons:

    st_crs(ailaoshan.polygons)
    proj4string(ailaoshan.srtm.reproj)

    extent(ailaoshan.polygons)
    extent(ailaoshan.srtm.reproj)

#### rasterize ####
    ailaoshan.polygons.rast <- fasterize(ailaoshan.polygons, ailaoshan.srtm.reproj)
    ailaoshan.polygons.rast <- ailaoshan.polygons.rast * ailaoshan.srtm.reproj + 1
```

```{r}
save(ailaoshan.polygons, ailaoshan.polygons.crs, ailaoshan.polygons.rast, ailaoshan.srtm, ailaoshan.srtm.crop, ailaoshan.srtm.reproj,
     file="ailaoshan_gis.Rdata")
```
