---
title: "Untitled"
author: "Chris Baker"
date: "11/02/2019"
output: html_document
---
# makes 3D plots and movies -- potentially with results overlaid but in practice this seems not to work so well.

# see e.g.https://datacarpentry.org/r-raster-vector-geospatial/06-vector-open-shapefile-in-r/
# and https://www.ecologi.st/post/spatial-data-in-r-2-a-practical-example/

# Note. download DEM data from USGS earth explorer:
# https://earthexplorer.usgs.gov

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(root.dir="/Users/chris/Documents/work/leeches/leeches2018/gis")
```

```{r}
#install.packages("sf")
library("sf")
library("gplots")
library("ggrepel")
library("readxl")
library("viridis")
library("raster")
#library("rgdal")
#install.packages("spData")
library("fasterize")
library("rasterVis")
library("rgl")
library("magick")
library("tidyverse")
library("egg")
```

```{r}
rm(list=ls())
```

```{r get data}
# Ailaoshan polygons and SRTM data already processed by Ailaoshan_gis.Rmd
    load(file="Ailaoshan_gis.Rdata")

#Ailaoshan raw and modelled data
    # load(file="../Ailaoshan_OTU_table.Rdata")
    # load(file="Ailaoshan_occupancy_slides4doug.Rdata")
```

```{r examine Ailaoshan polygons, eval=FALSE}
st_geometry_type(ailaoshan.polygons)
st_crs(ailaoshan.polygons)
extent(ailaoshan.polygons)

ailaoshan.polygons %>%
    ggplot() + geom_sf(size = 0.1, color = "black", fill = "burlywood2") + ggtitle("Ailaoshan") + coord_sf()
```

```{r make 3D plots}
# set window size
    #par3d(windowRect = c(200, 000, 1200, 1000))

# user matrix for setting viewpoint
    # um <- par3d()$userMatrix
    um <- matrix(data = c(0.97, 0.23, 0.01, 0,
        -0.13, 0.51, 0.85, 0,
        0.19, -0.83, 0.52, 0,
        0, 0, 0, 1), nrow=4, ncol=4, byrow=TRUE)
    view3d(userMatrix = um)

# red on colour terrain
    plot3D(ailaoshan.srtm.reproj, drape=ailaoshan.srtm.reproj, zfac=3, adjust=FALSE)
    plot3D(ailaoshan.polygons.rast, drape=ailaoshan.polygons.rast, zfac=3, adjust=FALSE, col="red")
    rgl.snapshot("figures/ailaoshan_site_colour.png", fmt = "png")
# red on grey
    rgl.clear()
    plot3D(ailaoshan.srtm.reproj, drape=ailaoshan.srtm.reproj, zfac=3, adjust=FALSE, col=gray(seq(0.6,1,0.01)))
    plot3D(ailaoshan.polygons.rast, drape=ailaoshan.polygons.rast, zfac=3, adjust=FALSE, col="red")
    rgl.snapshot("figures/ailaoshan_site_grey.png", fmt = "png")
# make movie
    movie3d(spin3d(axis = c(0, 0, 1), rpm = 10), duration = 6, fps = 25, movie="ailaoshan_site",
        dir = "figures")
```
