---
title: "Ailaoshan_descriptive.Rmd"
author: "Chris Baker"
email: "bakerccm@gmail.com"
date: "18/07/2018"
output: html_document
---

```{r setup, include=FALSE}
library("tidyverse")
library("gplots")
library("vegan")
```

```{r clear old variables, include=FALSE}
rm(list=ls())
```

```{r read in raw data and MCMC output, include=FALSE}
# generated with Ailaoshan_OTU_table.Rmd
# already includes environmental data, since that is processed
# prior to Ailaoshan_OTU_table.Rmd and loaded as part of that
    load(file="../Ailaoshan_OTU_table.Rdata")
```

```{r breakdown by taxonomic class}
leech %>%
    distinct(dataset, consensus.class, consensus.short) %>%
    group_by(dataset, consensus.class) %>% 
    ggplot(aes(x = consensus.class, fill=consensus.class)) + stat_count(show.legend = FALSE) + facet_wrap("dataset") +
    labs(x = "Class", y = "Number of species") + 
    theme(axis.text.x = element_text(angle=45, hjust=1))
ggsave(filename = "figures/Fig2a_taxonomic_breakdown.pdf", width = 4, height=3)
```

```{r rarefaction curves - collate data}
# LabID-wise species accumulation curves
    # make wide-format incidence tables
        LSU.Lab_ID.incidence <- leech %>% filter(dataset == "LSU") %>%
            mutate(LabID.incidence = ifelse(reads > 0, 1, 0)) %>% select(Lab_ID, OTU, LabID.incidence) %>%
            spread(key = OTU, value = LabID.incidence) %>% select(-Lab_ID)
        SSU.Lab_ID.incidence <- leech %>% filter(dataset == "SSU") %>%
            mutate(LabID.incidence = ifelse(reads > 0, 1, 0)) %>% select(Lab_ID, OTU, LabID.incidence) %>%
            spread(key = OTU, value = LabID.incidence) %>% select(-Lab_ID)
        combined.Lab_ID.incidence <- leech %>%
            # summarize by consensus.short to avoid double counting OTUs when both datasets included
                group_by(Lab_ID, consensus.short) %>%
                summarize(LabID.incidence = ifelse(sum(reads) > 0, 1, 0)) %>%
                ungroup() %>%
            # convert to wide format data
                select(Lab_ID, consensus.short, LabID.incidence) %>%
                spread(key = consensus.short, value = LabID.incidence, fill = 0) %>% select(-Lab_ID)
    # calculate accumulation curves
        lsu.specaccum.LabID <- specaccum(comm = LSU.Lab_ID.incidence)
        ssu.specaccum.LabID <- specaccum(comm = SSU.Lab_ID.incidence)
        combined.specaccum.LabID <- specaccum(comm = combined.Lab_ID.incidence)
        
        str(combined.specaccum.LabID)
        
    # bind together into a single tibble
        specaccum.LabID <- bind_rows(
            LSU = tibble(
                sites = lsu.specaccum.LabID$sites,
                richness = lsu.specaccum.LabID$richness,
                sd = lsu.specaccum.LabID$sd
            ),
            SSU = tibble(
                sites = ssu.specaccum.LabID$sites,
                richness = ssu.specaccum.LabID$richness,
                sd = ssu.specaccum.LabID$sd
            ),
            combined = tibble(
                sites = combined.specaccum.LabID$sites,
                richness = combined.specaccum.LabID$richness,
                sd = combined.specaccum.LabID$sd
            ),
            .id = "dataset"
        )
        specaccum.LabID <- specaccum.LabID %>% mutate(dataset = factor(dataset, levels = c("combined", "SSU", "LSU")))  # use this to flip order of legend and colours ?
    # clean up
        rm(LSU.Lab_ID.incidence, SSU.Lab_ID.incidence, combined.Lab_ID.incidence, lsu.specaccum.LabID, ssu.specaccum.LabID, combined.specaccum.LabID)

# PolygonID-wise species accumulation curves
    # make wide-format incidence tables
        LSU.Polygon_ID.incidence <- leech %>% filter(dataset == "LSU") %>%
            group_by(Polygon_ID, OTU) %>% summarise(polygon.incidence = ifelse(sum(reads) > 0, 1, 0)) %>% ungroup() %>%
            spread(key = OTU, value = polygon.incidence) %>% select(-Polygon_ID)
        SSU.Polygon_ID.incidence <- leech %>% filter(dataset == "SSU") %>%
            group_by(Polygon_ID, OTU) %>% summarise(polygon.incidence = ifelse(sum(reads) > 0, 1, 0)) %>% ungroup() %>%
            spread(key = OTU, value = polygon.incidence) %>% select(-Polygon_ID)
        combined.Polygon_ID.incidence <- leech %>%
            # summarize by consensus.short to avoid double counting OTUs when both datasets included
                group_by(Polygon_ID, consensus.short) %>%
                summarize(polygon.incidence = ifelse(sum(reads) > 0, 1, 0)) %>% ungroup() %>%
            # convert to wide format data
                select(Polygon_ID, consensus.short, polygon.incidence) %>%
                spread(key = consensus.short, value = polygon.incidence, fill = 0) %>% select(-Polygon_ID)
    # calculate accumulation curves
        lsu.specaccum.PolygonID <- specaccum(comm = LSU.Polygon_ID.incidence)
        ssu.specaccum.PolygonID <- specaccum(comm = SSU.Polygon_ID.incidence)
        combined.specaccum.PolygonID <- specaccum(comm = combined.Polygon_ID.incidence)
    # bind together into a single tibble
        specaccum.PolygonID <- bind_rows(
            LSU = tibble(
                sites = lsu.specaccum.PolygonID$sites,
                richness = lsu.specaccum.PolygonID$richness,
                sd = lsu.specaccum.PolygonID$sd
            ),
            SSU = tibble(
                sites = ssu.specaccum.PolygonID$sites,
                richness = ssu.specaccum.PolygonID$richness,
                sd = ssu.specaccum.PolygonID$sd
            ),
            combined = tibble(
                sites = combined.specaccum.PolygonID$sites,
                richness = combined.specaccum.PolygonID$richness,
                sd = combined.specaccum.PolygonID$sd
            ),
            .id = "dataset"
        )
        specaccum.PolygonID <- specaccum.PolygonID %>% mutate(dataset = factor(dataset, levels = c("combined", "SSU", "LSU")))
    # clean up
        rm(LSU.Polygon_ID.incidence, SSU.Polygon_ID.incidence, combined.Polygon_ID.incidence, lsu.specaccum.PolygonID, ssu.specaccum.PolygonID, combined.specaccum.PolygonID)
```

```{r rarefaction curves - draw plots}
specaccum.LabID %>%
    ggplot(aes(x=sites, y=richness, col=dataset)) +
        geom_line() +
        geom_ribbon(aes(ymin = richness - sd, ymax= richness + sd, fill=dataset), alpha=0.4, col=NA) +
        labs(x="number of replicates", y= "observed species richness", fill="Dataset", color="Dataset") +
        theme(legend.justification=c(1,0), legend.position=c(0.96,0.05))
ggsave("figures/Fig2b_LabID_rarefaction.pdf", width = 4, height = 4)

specaccum.PolygonID %>%
    ggplot(aes(x=sites, y=richness, col=dataset)) +
        geom_line() +
        geom_ribbon(aes(ymin = richness - sd, ymax= richness + sd, fill=dataset), alpha=0.4, col=NA) +
        labs(x="number of patrol areas", y= "observed species richness", fill="Dataset", color="Dataset") +
        theme(legend.justification=c(1,0), legend.position=c(0.96,0.05))
#ggsave("figures/FigXX_PolygonID_rarefaction.pdf", width = 4, height = 4)  # not currently used

rm(specaccum.LabID, specaccum.PolygonID)
```

```{r}

```

