---
title: "Ailaoshan_occupancy_analyze_Fig3_richness.Rmd"
author: "Chris Baker"
email: "bakerccm@gmail.com"
date: "22/11/2019"
output: html_document
---

```{r setup, include=FALSE}
library("tidyverse")
```

```{r clear old variables, include=FALSE}
rm(list=ls())
```

```{r read in MCMC output and GIS output for drawing maps, include=FALSE}
# generated with Ailaoshan_OTU_table.Rmd
    load(file="../Ailaoshan_OTU_table.Rdata")

# MCMC output generated with Ailaoshan_occupancy_postprocess_cluster.Rmd
    load(file="Ailaoshan_occupancy_postprocess_cluster.Rdata")

# Ailaoshan processed GIS data
    load(file="../gis/ailaoshan_gis.Rdata")
```

```{r Figure 3a,3b observed richness}
## add observed richness data to ailaoshan.polygons sf object

observed.OTU.richness <- leech %>%
    group_by(dataset, Polygon_ID, OTU) %>%
    summarize(OTU.observed = ifelse(sum(reads) > 0, 1, 0)) %>%
    group_by(dataset, Polygon_ID) %>%
    summarize(richness = sum(OTU.observed)) %>%
    ungroup() %>%
    pivot_wider(id_cols = Polygon_ID, values_from = richness, names_prefix = "observed.richness.", names_from = dataset)

ailaoshan.polygons <- ailaoshan.polygons %>%
        mutate(Polygon_ID = as.character(Polygon_ID)) %>%
        left_join(observed.OTU.richness, by="Polygon_ID")

## add estimated richness data to ailaoshan.polygons sf object

estimated.OTU.richness <- bind_rows(
        Nsite.output$LSU$model23a %>% mutate(dataset = "LSU") %>% select(dataset, Polygon_ID, mean),
        Nsite.output$SSU$model23a %>% mutate(dataset = "SSU") %>% select(dataset, Polygon_ID, mean)) %>%
    pivot_wider(id_cols = Polygon_ID, values_from = mean, names_prefix = "estimated.richness.", names_from = dataset)

ailaoshan.polygons <- ailaoshan.polygons %>%
    left_join(estimated.OTU.richness, by="Polygon_ID")

```

```{r draw observed richness plots }
# Fig 3a: LSU observed richness
    ailaoshan.polygons %>%
        ggplot() + geom_sf(aes(fill=observed.richness.LSU), size = 0.1, color = "black") +
            theme(legend.position=c(0,0), legend.justification=c(0,0), legend.background = element_rect(fill=NA)) +
            coord_sf() + labs(fill = "LSU\nobserved\nspecies\nrichness") + scale_fill_continuous(na.value=NA)
    ggsave("figures/Fig3a_LSU_obsvrich.pdf", width=4, height=4)
# Fig 3b: SSU observed richness
    ailaoshan.polygons %>%
        ggplot() + geom_sf(aes(fill=observed.richness.SSU), size = 0.1, color = "black") +
            theme(legend.position=c(0,0), legend.justification=c(0,0), legend.background = element_rect(fill=NA)) +
            coord_sf() + labs(fill = "SSU\nobserved\nspecies\nrichness") + scale_fill_continuous(na.value=NA)
    ggsave("figures/Fig3b_SSU_obsvrich.pdf", width=4, height=4)
```

```{r draw model richness plots }
# Fig 3c: LSU model richness
    ailaoshan.polygons %>%
        ggplot() + geom_sf(aes(fill=estimated.richness.LSU), size = 0.1, color = "black") +
            theme(legend.position=c(0,0), legend.justification=c(0,0), legend.background = element_rect(fill=NA)) +
            coord_sf() + labs(fill = "LSU\nestimated\nspecies\nrichness") + scale_fill_continuous(na.value=NA)
    ggsave("figures/Fig3c_LSU_model23a_richness.pdf", width=4, height=4)
# Fig 3d: SSU model richness
    ailaoshan.polygons %>%
        ggplot() + geom_sf(aes(fill=estimated.richness.SSU), size = 0.1, color = "black") +
            theme(legend.position=c(0,0), legend.justification=c(0,0), legend.background = element_rect(fill=NA)) +
            coord_sf() + labs(fill = "SSU\nestimated\nspecies\nrichness") + scale_fill_continuous(na.value=NA)
    ggsave("figures/Fig3d_SSU_model23a_richness.pdf", width=4, height=4)
```

```{r histograms of per-PolygonID species richness}
# prepare data for plotting -- group by dataset

OTU.richness <- inner_join(observed.OTU.richness, estimated.OTU.richness, by = "Polygon_ID") %>%
    filter(complete.cases(.)) %>%
    pivot_longer(-Polygon_ID, names_to = c("source", NA, "dataset"), names_sep = "\\.", values_to = "richness")

OTU.richness.medians <- OTU.richness %>% group_by(`source`, dataset) %>%
    summarise(median.richness = median(richness))
```


```{r}
LSU.medians <- OTU.richness.medians %>% filter(dataset == "LSU")
SSU.medians <- OTU.richness.medians %>% filter(dataset == "SSU")

# plot Fig 3e: LSU richness
    OTU.richness %>% filter(dataset == "LSU") %>%
        ggplot(aes(x = richness, color = source)) +
            geom_histogram(fill = "white", alpha = 0.5, position = "identity", binwidth = 2) + xlim(0,35) + ylim(0,55) +
            geom_vline(data = LSU.medians, aes(xintercept = median.richness, color = source), linetype = "dashed") +
            labs(x = "LSU species richness") +
            theme(legend.title = element_blank(), legend.position = c(0.8, 0.7)) +
            geom_label(data = LSU.medians, aes(x = median.richness, y = 54,
                label = paste0("median = ", round(LSU.medians$median.richness, 1))), show.legend = FALSE, size = 3)
    ggsave("figures/Fig3e_LSU_richhist.pdf", width=4, height=3)

# plot Fig 3f: SSU richness
    OTU.richness %>% filter(dataset == "SSU") %>%
        ggplot(aes(x = richness, color = source)) +
            geom_histogram(fill = "white", alpha = 0.5, position = "identity", binwidth = 2) + xlim(0,35) + ylim(0,55) +
            geom_vline(data = SSU.medians, aes(xintercept = median.richness, color = source), linetype = "dashed") +
            labs(x = "SSU species richness") + 
            theme(legend.title = element_blank(), legend.position = c(0.8, 0.7)) +
            geom_label(data = SSU.medians, aes(x = median.richness, y = 54,
                label = paste0("median = ", round(SSU.medians$median.richness, 1))), show.legend = FALSE, size = 3)
    ggsave("figures/Fig3f_SSU_richhist.pdf", width=4, height=3)

rm(LSU.medians, SSU.medians)
```

```{r}
# how many observed species per replicate (i.e. LabID)?
leech %>% filter(!is.na(leech_qty)) %>%
        group_by(dataset, Lab_ID) %>%
        summarize(observed.richness = sum(ifelse(reads > 0, 1, 0))) %>%
        group_by(dataset) %>%
        summarize(median.observed.richness = median(observed.richness))
```

```{r}
# how many replicates per polygonID?
leech %>% filter(!is.na(leech_qty)) %>%
        group_by(dataset, Polygon_ID, OTU) %>%
        summarize(num.replicates = n()) %>%
        group_by(dataset, Polygon_ID) %>%
        summarize(num.replicates = mean(num.replicates)) %>%
        group_by(dataset) %>%
        summarize(num.replicates = round(median(num.replicates), 1))
```

```{r}

```

